# Generated by Django 5.2.14 on 2026-05-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name_plural': 'Enrolled'},
        ),
    ]
